version: '3.8'
services:
  vue:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: time_manager_vue
    ports:
      - "8081:8080"
    volumes:
      - ../frontend:/app
    networks:
      - time_manager_network
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=reverse-proxy-docker-traefik_routing"
      # https
      - "traefik.http.routers.vue.rule=Host(`time_manager.orbesle.fr`)"  # Replace with actual domain
      - "traefik.http.routers.vue.tls=true"
      - "traefik.http.routers.vue.tls.certresolver=letsencrypt"
      - "traefik.http.routers.vue.entrypoints=websecure"
      # http (redirect to https)
      - "traefik.http.routers.vue-http.rule=Host(`home.orbesle.fr)"  # Replace with actual domain
      - "traefik.http.routers.vue-http.entrypoints=web"
      - "traefik.http.routers.vue-http.middlewares=redirect-to-https@file"

  db:
    image: postgres:14-alpine
    container_name: time_manager_db
    environment:
      POSTGRES_USER: gotham_admin
      POSTGRES_PASSWORD: gotham_password
      POSTGRES_DB: time_manager
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - time_manager_network
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gotham_admin"]
      interval: 10s
      retries: 5

  web:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: time_manager_web
    depends_on:
      db:
        condition: service_healthy
    environment:
      MIX_ENV: dev
      DATABASE_URL: "ecto://gotham_admin:gotham_password@db/time_manager"
    ports:
      - "4000:4000"
    volumes:
      - ../time_manager:/time_manager
    networks:
      - time_manager_network
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=reverse-proxy-docker-traefik_routing"
      # https
      - "traefik.http.routers.web.rule=Host(`api.orbesle.fr`)"  # Replace with actual domain
      - "traefik.http.routers.web.tls=true"
      - "traefik.http.routers.web.tls.certresolver=letsencrypt"
      - "traefik.http.routers.web.entrypoints=websecure"
      # http (redirect to https)
      - "traefik.http.routers.web-http.rule=Host(`api.orbesle.fr`)"  # Replace with actual domain
      - "traefik.http.routers.web-http.entrypoints=web"
      - "traefik.http.routers.web-http.middlewares=redirect-to-https@file"

volumes:
  pgdata:

networks:
  time_manager_network:
    external: true
    name: reverse-proxy-docker-traefik_routing
